### ISSUE TITLE
CollectionName is not defined

### ISSUE THREAD

**Issue by Unforgiven-wanda** [PeterChauYEG/meteor-react-base#2]
Hello,
I'm having a strange issue where whenever I try to declare a new collection (be it in a file at the root of my project, or inside the lib folder) I get the following error : ReferenceError: PlayersList is not defined at meteorInstall.collections.js (collections.js:2:1).

The issue abates when I add "var" but I need to be able to access this collection later on.
I've never had a similar issue when using Meter 1.2 and it's driving me crazy.

**Comment by PeterChauYEG** [comment]
Hey there,

Would you mind sharing the code or repo? Also, how are you calling the collection?

There could be a few reasons for this issue.

**Comment by Unforgiven-wanda** [comment]
Hi, and thanks for answering.
Here you can see a project I started on c9 https://ide.c9.io/samirhabib/meteorreact 
It is public so you should be able to see it. In any case, I simply have 3 new files : server.js in server folder (for inserting something then publishing), client.js in client folder (for subscribing), and collections.js at the root of my project. When all files are empty the project starts fine, but when adding : `PlayersList = new Mongo.Collection('players');
` I immediately have the following error "ReferenceError: PlayersList is not defined"

As you see, I'm at a loss here.
Again, thank you.

**Comment by Unforgiven-wanda** [comment]
I have finally found out what went wrong. The issue is not with your repo (which is by the way fantastic) but with the Meteor 1.3 as yet scarce documentation itself. Declared collections are no longer global by default, as in 1.2, meaning I have to export them then import them elsewhere to be able to use them, like so:

```
//  lib/collections.js : 
const Rooms = new Mongo.Collection('rooms')
export default Rooms
```

And then

//  server/server.js
```
import Rooms from '/lib/collections.js';

Rooms.insert({
    name: "test"
});
Rooms.insert({
    name: "Another test"
});
```

Hoping this helps someone else. I close this issue.
